[package]
name = "Delta-Notes-Endpoint"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"] }
dotenv = "0.15.0"
dotenvy = "0.15.7"
serde = "1.0.199"
serde_json = "1.0.116"
shuttle-runtime = "0.44.0"
shuttle-shared-db = { version = "0.44.0", features = ["postgres"] }
shuttle-tide = "0.44.0"
sqlx = "0.7.4"
tide = "0.16.0"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.10"
unofficial_appwrite = "0.1.0"

